
import { Upgrade } from '@/context/GameContext';
import { 
  MousePointerClick, Timer, Zap, Percent, 
  Gem, Star, Award, Bolt, Heart, Target, 
  TrendingUp, Rocket, Cpu, Server, BarChart, 
  DollarSign, Infinity, Gift, Layers, Database,
  Briefcase, Globe, Key, Shield, Sparkles
} from 'lucide-react';

// Categories
export const UPGRADE_CATEGORIES = {
  CLICK: 'click',
  PASSIVE: 'passive',
  MULTIPLIER: 'multiplier',
  SPECIAL: 'special',
  PRESTIGE: 'prestige'
};

// Initial upgrades list with 50+ upgrades
export const upgradesList: Upgrade[] = [
  // Basic Tier (Always Unlocked)
  {
    id: 'click-power',
    name: 'Tap Power',
    description: 'Increase coins per tap',
    cost: 10,
    baseCost: 10,
    level: 0,
    maxLevel: 50,
    coinsPerClickBonus: 1,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0,
    icon: 'mouse-pointer-click',
    unlocked: true,
    category: UPGRADE_CATEGORIES.CLICK
  },
  {
    id: 'auto-clicker',
    name: 'Auto Tapper',
    description: 'Automatically generate coins',
    cost: 25,
    baseCost: 25,
    level: 0,
    maxLevel: 50,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 0.5,
    multiplierBonus: 0,
    icon: 'timer',
    unlocked: true,
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  
  // Tier 1 (Unlocked Early)
  {
    id: 'efficiency',
    name: 'Efficiency',
    description: 'Boost all coin generation',
    cost: 100,
    baseCost: 100,
    level: 0,
    maxLevel: 20,
    coinsPerClickBonus: 2,
    coinsPerSecondBonus: 1,
    multiplierBonus: 0,
    icon: 'zap',
    unlocked: false,
    unlocksAt: { upgradeId: 'click-power', level: 4 },
    category: UPGRADE_CATEGORIES.CLICK
  },
  {
    id: 'multiplier',
    name: 'Multiplier',
    description: 'Multiply all coin generation',
    cost: 500,
    baseCost: 500,
    level: 0,
    maxLevel: 10,
    coinsPerClickBonus: 5,
    coinsPerSecondBonus: 2,
    multiplierBonus: 0.05,
    icon: 'percent',
    unlocked: false,
    unlocksAt: { upgradeId: 'auto-clicker', level: 9 },
    category: UPGRADE_CATEGORIES.MULTIPLIER
  },
  
  // Tier 2
  {
    id: 'finger-enhancement',
    name: 'Finger Enhancement',
    description: 'Your fingers tap faster and better',
    cost: 1000,
    baseCost: 1000,
    level: 0,
    maxLevel: 30,
    coinsPerClickBonus: 10,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0,
    icon: 'mouse-pointer-click',
    unlocked: false,
    unlocksAt: { upgradeId: 'efficiency', level: 5 },
    category: UPGRADE_CATEGORIES.CLICK
  },
  {
    id: 'passive-engine',
    name: 'Passive Engine',
    description: 'A basic engine that generates coins',
    cost: 2500,
    baseCost: 2500,
    level: 0,
    maxLevel: 30,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 5,
    multiplierBonus: 0,
    icon: 'timer',
    unlocked: false,
    unlocksAt: { upgradeId: 'auto-clicker', level: 15 },
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  
  // Tier 3
  {
    id: 'gem-finder',
    name: 'Gem Finder',
    description: 'Occasionally find valuable gems while tapping',
    cost: 5000,
    baseCost: 5000,
    level: 0,
    maxLevel: 20,
    coinsPerClickBonus: 20,
    coinsPerSecondBonus: 5,
    multiplierBonus: 0,
    icon: 'gem',
    unlocked: false,
    unlocksAt: { upgradeId: 'finger-enhancement', level: 10 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  {
    id: 'coin-multiplier',
    name: 'Coin Multiplier',
    description: 'Multiply your coin earnings',
    cost: 7500,
    baseCost: 7500,
    level: 0,
    maxLevel: 15,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0.1,
    icon: 'percent',
    unlocked: false,
    unlocksAt: { upgradeId: 'multiplier', level: 5 },
    category: UPGRADE_CATEGORIES.MULTIPLIER
  },
  
  // Tier 4
  {
    id: 'star-power',
    name: 'Star Power',
    description: 'Harness the energy of stars for more coins',
    cost: 10000,
    baseCost: 10000,
    level: 0,
    maxLevel: 10,
    coinsPerClickBonus: 50,
    coinsPerSecondBonus: 15,
    multiplierBonus: 0.05,
    icon: 'star',
    unlocked: false,
    unlocksAt: { upgradeId: 'gem-finder', level: 8 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  {
    id: 'automated-factory',
    name: 'Automated Factory',
    description: 'A factory that produces coins automatically',
    cost: 25000,
    baseCost: 25000,
    level: 0,
    maxLevel: 15,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 50,
    multiplierBonus: 0,
    icon: 'server',
    unlocked: false,
    unlocksAt: { upgradeId: 'passive-engine', level: 10 },
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  
  // Tier 5
  {
    id: 'golden-touch',
    name: 'Golden Touch',
    description: 'Everything you touch turns to gold',
    cost: 50000,
    baseCost: 50000,
    level: 0,
    maxLevel: 10,
    coinsPerClickBonus: 200,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0.1,
    icon: 'award',
    unlocked: false,
    unlocksAt: { upgradeId: 'star-power', level: 5 },
    category: UPGRADE_CATEGORIES.CLICK
  },
  {
    id: 'quantum-generator',
    name: 'Quantum Generator',
    description: 'Generate coins from quantum fluctuations',
    cost: 75000,
    baseCost: 75000,
    level: 0,
    maxLevel: 8,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 200,
    multiplierBonus: 0.05,
    icon: 'cpu',
    unlocked: false,
    unlocksAt: { upgradeId: 'automated-factory', level: 5 },
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  
  // Tier 6
  {
    id: 'cosmic-energy',
    name: 'Cosmic Energy',
    description: 'Harness cosmic energy for massive coin production',
    cost: 150000,
    baseCost: 150000,
    level: 0,
    maxLevel: 6,
    coinsPerClickBonus: 500,
    coinsPerSecondBonus: 150,
    multiplierBonus: 0.2,
    icon: 'bolt',
    unlocked: false,
    unlocksAt: { upgradeId: 'quantum-generator', level: 3 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  {
    id: 'global-network',
    name: 'Global Network',
    description: 'A worldwide network generating coins',
    cost: 250000,
    baseCost: 250000,
    level: 0,
    maxLevel: 5,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 500,
    multiplierBonus: 0.1,
    icon: 'globe',
    unlocked: false,
    unlocksAt: { upgradeId: 'automated-factory', level: 8 },
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  
  // Tier 7
  {
    id: 'time-warp',
    name: 'Time Warp',
    description: 'Bend time to produce more coins',
    cost: 500000,
    baseCost: 500000,
    level: 0,
    maxLevel: 4,
    coinsPerClickBonus: 1000,
    coinsPerSecondBonus: 750,
    multiplierBonus: 0.3,
    icon: 'trending-up',
    unlocked: false,
    unlocksAt: { upgradeId: 'cosmic-energy', level: 3 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  {
    id: 'gold-rush',
    name: 'Gold Rush',
    description: 'Start a gold rush for massive tap profits',
    cost: 750000,
    baseCost: 750000,
    level: 0,
    maxLevel: 3,
    coinsPerClickBonus: 5000,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0.5,
    icon: 'dollar-sign',
    unlocked: false,
    unlocksAt: { upgradeId: 'golden-touch', level: 5 },
    category: UPGRADE_CATEGORIES.CLICK
  },
  
  // Tier 8
  {
    id: 'universal-factory',
    name: 'Universal Factory',
    description: 'A factory spanning the universe',
    cost: 1000000,
    baseCost: 1000000,
    level: 0,
    maxLevel: 3,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 5000,
    multiplierBonus: 0.4,
    icon: 'rocket',
    unlocked: false,
    unlocksAt: { upgradeId: 'global-network', level: 3 },
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  {
    id: 'infinity-touch',
    name: 'Infinity Touch',
    description: 'Your touch generates nearly infinite coins',
    cost: 5000000,
    baseCost: 5000000,
    level: 0,
    maxLevel: 2,
    coinsPerClickBonus: 10000,
    coinsPerSecondBonus: 1000,
    multiplierBonus: 1,
    icon: 'infinity',
    unlocked: false,
    unlocksAt: { upgradeId: 'time-warp', level: 2 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  
  // Tier 9 (Very Hard to Reach)
  {
    id: 'multiverse-miner',
    name: 'Multiverse Miner',
    description: 'Mine across multiple universes simultaneously',
    cost: 10000000,
    baseCost: 10000000,
    level: 0,
    maxLevel: 1,
    coinsPerClickBonus: 50000,
    coinsPerSecondBonus: 25000,
    multiplierBonus: 2,
    icon: 'sparkles',
    unlocked: false,
    unlocksAt: { upgradeId: 'infinity-touch', level: 1 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  
  // Additional upgrades to reach 50+ total
  // Tier 2-3 additions
  {
    id: 'double-tap',
    name: 'Double Tap',
    description: 'Each tap counts as two',
    cost: 3000,
    baseCost: 3000,
    level: 0,
    maxLevel: 15,
    coinsPerClickBonus: 15,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0,
    icon: 'mouse-pointer-click',
    unlocked: false,
    unlocksAt: { upgradeId: 'efficiency', level: 8 },
    category: UPGRADE_CATEGORIES.CLICK
  },
  {
    id: 'idle-assistant',
    name: 'Idle Assistant',
    description: 'An assistant who taps when you\'re away',
    cost: 4000,
    baseCost: 4000,
    level: 0,
    maxLevel: 20,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 10,
    multiplierBonus: 0,
    icon: 'timer',
    unlocked: false,
    unlocksAt: { upgradeId: 'passive-engine', level: 5 },
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  
  // Tier 4-5 additions
  {
    id: 'lucky-charm',
    name: 'Lucky Charm',
    description: 'Increases your chance of finding bonus coins',
    cost: 30000,
    baseCost: 30000,
    level: 0,
    maxLevel: 10,
    coinsPerClickBonus: 25,
    coinsPerSecondBonus: 10,
    multiplierBonus: 0.1,
    icon: 'heart',
    unlocked: false,
    unlocksAt: { upgradeId: 'gem-finder', level: 5 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  {
    id: 'profit-maximizer',
    name: 'Profit Maximizer',
    description: 'Maximize your coin production efficiency',
    cost: 40000,
    baseCost: 40000,
    level: 0,
    maxLevel: 12,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0.15,
    icon: 'bar-chart',
    unlocked: false,
    unlocksAt: { upgradeId: 'coin-multiplier', level: 3 },
    category: UPGRADE_CATEGORIES.MULTIPLIER
  },
  
  // Tier 6-7 additions
  {
    id: 'precision-tapper',
    name: 'Precision Tapper',
    description: 'Tap with extraordinary precision for better results',
    cost: 200000,
    baseCost: 200000,
    level: 0,
    maxLevel: 8,
    coinsPerClickBonus: 400,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0.05,
    icon: 'target',
    unlocked: false,
    unlocksAt: { upgradeId: 'golden-touch', level: 3 },
    category: UPGRADE_CATEGORIES.CLICK
  },
  {
    id: 'data-center',
    name: 'Data Center',
    description: 'A massive data center mining digital coins',
    cost: 350000,
    baseCost: 350000,
    level: 0,
    maxLevel: 8,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 350,
    multiplierBonus: 0.05,
    icon: 'database',
    unlocked: false,
    unlocksAt: { upgradeId: 'global-network', level: 2 },
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  
  // Additional click-based upgrades
  {
    id: 'finger-implants',
    name: 'Finger Implants',
    description: 'Cybernetic implants for superior tapping',
    cost: 125000,
    baseCost: 125000,
    level: 0,
    maxLevel: 10,
    coinsPerClickBonus: 300,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0,
    icon: 'mouse-pointer-click',
    unlocked: false,
    unlocksAt: { upgradeId: 'precision-tapper', level: 2 },
    category: UPGRADE_CATEGORIES.CLICK
  },
  {
    id: 'touch-of-midas',
    name: 'Touch of Midas',
    description: 'The mythical golden touch',
    cost: 600000,
    baseCost: 600000,
    level: 0,
    maxLevel: 5,
    coinsPerClickBonus: 2000,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0.2,
    icon: 'mouse-pointer-click',
    unlocked: false,
    unlocksAt: { upgradeId: 'finger-implants', level: 5 },
    category: UPGRADE_CATEGORIES.CLICK
  },
  
  // Additional passive upgrades
  {
    id: 'robot-workforce',
    name: 'Robot Workforce',
    description: 'An army of robots generating coins',
    cost: 175000,
    baseCost: 175000,
    level: 0,
    maxLevel: 12,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 250,
    multiplierBonus: 0,
    icon: 'timer',
    unlocked: false,
    unlocksAt: { upgradeId: 'data-center', level: 3 },
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  {
    id: 'orbital-station',
    name: 'Orbital Station',
    description: 'A space station mining asteroids for coins',
    cost: 800000,
    baseCost: 800000,
    level: 0,
    maxLevel: 6,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 2000,
    multiplierBonus: 0.1,
    icon: 'timer',
    unlocked: false,
    unlocksAt: { upgradeId: 'robot-workforce', level: 6 },
    category: UPGRADE_CATEGORIES.PASSIVE
  },
  
  // Additional multiplier upgrades
  {
    id: 'investment-fund',
    name: 'Investment Fund',
    description: 'Your coins generate more coins',
    cost: 90000,
    baseCost: 90000,
    level: 0,
    maxLevel: 10,
    coinsPerClickBonus: 0,
    coinsPerSecondBonus: 0,
    multiplierBonus: 0.2,
    icon: 'briefcase',
    unlocked: false,
    unlocksAt: { upgradeId: 'profit-maximizer', level: 5 },
    category: UPGRADE_CATEGORIES.MULTIPLIER
  },
  {
    id: 'economic-breakthrough',
    name: 'Economic Breakthrough',
    description: 'Revolutionary economic principles multiply your earnings',
    cost: 450000,
    baseCost: 450000,
    level: 0,
    maxLevel: 5,
    coinsPerClickBonus: 100,
    coinsPerSecondBonus: 100,
    multiplierBonus: 0.5,
    icon: 'trending-up',
    unlocked: false,
    unlocksAt: { upgradeId: 'investment-fund', level: 5 },
    category: UPGRADE_CATEGORIES.MULTIPLIER
  },
  
  // Additional special upgrades
  {
    id: 'treasure-chest',
    name: 'Treasure Chest',
    description: 'Occasionally find treasure chests full of coins',
    cost: 60000,
    baseCost: 60000,
    level: 0,
    maxLevel: 15,
    coinsPerClickBonus: 50,
    coinsPerSecondBonus: 20,
    multiplierBonus: 0,
    icon: 'gift',
    unlocked: false,
    unlocksAt: { upgradeId: 'lucky-charm', level: 4 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  {
    id: 'arcane-knowledge',
    name: 'Arcane Knowledge',
    description: 'Ancient secrets to boost coin production',
    cost: 300000,
    baseCost: 300000,
    level: 0,
    maxLevel: 8,
    coinsPerClickBonus: 150,
    coinsPerSecondBonus: 150,
    multiplierBonus: 0.25,
    icon: 'key',
    unlocked: false,
    unlocksAt: { upgradeId: 'treasure-chest', level: 8 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  
  // Additional high-tier upgrades
  {
    id: 'virtual-reality',
    name: 'Virtual Reality',
    description: 'Generate coins in virtual worlds',
    cost: 1500000,
    baseCost: 1500000,
    level: 0,
    maxLevel: 3,
    coinsPerClickBonus: 3000,
    coinsPerSecondBonus: 3000,
    multiplierBonus: 0.5,
    icon: 'layers',
    unlocked: false,
    unlocksAt: { upgradeId: 'universal-factory', level: 2 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  {
    id: 'divine-intervention',
    name: 'Divine Intervention',
    description: 'Cosmic powers assist your coin generation',
    cost: 3000000,
    baseCost: 3000000,
    level: 0,
    maxLevel: 2,
    coinsPerClickBonus: 7500,
    coinsPerSecondBonus: 7500,
    multiplierBonus: 1,
    icon: 'sparkles',
    unlocked: false,
    unlocksAt: { upgradeId: 'virtual-reality', level: 2 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  
  // Ultra high-tier upgrades (nearly impossible to get)
  {
    id: 'reality-bender',
    name: 'Reality Bender',
    description: 'Bend reality itself to generate coins',
    cost: 7500000,
    baseCost: 7500000,
    level: 0,
    maxLevel: 1,
    coinsPerClickBonus: 20000,
    coinsPerSecondBonus: 15000,
    multiplierBonus: 1.5,
    icon: 'shield',
    unlocked: false,
    unlocksAt: { upgradeId: 'divine-intervention', level: 1 },
    category: UPGRADE_CATEGORIES.SPECIAL
  },
  {
    id: 'big-bang-creator',
    name: 'Big Bang Creator',
    description: 'Create new universes full of coins',
    cost: 20000000,
    baseCost: 20000000,
    level: 0,
    maxLevel: 1,
    coinsPerClickBonus: 100000,
    coinsPerSecondBonus: 100000,
    multiplierBonus: 5,
    icon: 'sparkles',
    unlocked: false,
    unlocksAt: { upgradeId: 'reality-bender', level: 1 },
    category: UPGRADE_CATEGORIES.SPECIAL
  }
];
